### PR TITLE
fix warning in healthfacility

### PR DESCRIPTION
**Pull request by RobertoMaurizzi**
Fix `fields.W340` warning

### CODE REVIEW

**Review by PeteCoward — COMMENTED** [review]
Does this not need a migration? Or at least provoke one even if it is not needed?

**Comment by RobertoMaurizzi** [comment]
I would say that changing the last migration (0004_...) to not add the 'extra' condition is enough, since it's not really a database change (the null on an m2m relation is undefined, being the absence of a record and as such always possible) so you don't even need to run them again.
On my local computer with a fresh copy from production it worked (meaning, the warning went away and migrations are happy because the last migration matches with the model)

**Comment by PeteCoward** [comment]
Sorry, i missed that there was a migration change in there already.

**Review by PeteCoward — APPROVED** [review]

**Comment by RobertoMaurizzi** [comment]
It doesn't look like a (new) migration usually does :-)

**Pull request merged**
